
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.camila.pe.cpresentacion;
import com.camila.pe.cmodelo.Cliente;
import com.camila.pe.cnegocio.ClienteBO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class JPcliente extends javax.swing.JPanel {
    ClienteBO tdbo = new  ClienteBO();
    Cliente td = new Cliente();
     String DNI_CLIENTE;
    /**
     * Creates new form JPcliente
     */
     
    public JPcliente() {
        initComponents();
        listarCliente();
    }
  public void listarCliente(){
        tdbo.listarCliente(tablacliente);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        txtdni = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablacliente = new javax.swing.JTable();
        btnmodificar = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setText("REGISTRO CLIENTE");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 278, 64));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel2.setText("DNI");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 170, 36));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel3.setText("TELEFONO");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 170, 36));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel4.setText("NOMBRE ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 170, 36));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel5.setText("DIRECCION");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 170, 36));

        txtdireccion.setBorder(null);
        add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 220, 39));

        txttelefono.setBorder(null);
        add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 220, 39));

        txtdni.setBorder(null);
        add(txtdni, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 220, 39));

        txtnombre.setBorder(null);
        add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 220, 39));

        tablacliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablacliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaclienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablacliente);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 450, 380));

        btnmodificar.setBackground(new java.awt.Color(0, 153, 255));
        btnmodificar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnmodificar.setForeground(new java.awt.Color(255, 255, 255));
        btnmodificar.setText("MODIFICAR");
        btnmodificar.setBorder(null);
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });
        add(btnmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 530, 90, 40));

        btnlimpiar.setBackground(new java.awt.Color(0, 153, 255));
        btnlimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnlimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnlimpiar.setText("LIMPIAR");
        btnlimpiar.setBorder(null);
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });
        add(btnlimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 80, 40));

        btnguardar.setBackground(new java.awt.Color(0, 153, 255));
        btnguardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnguardar.setForeground(new java.awt.Color(255, 255, 255));
        btnguardar.setText("GUARDAR");
        btnguardar.setBorder(null);
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, 80, 40));

        btneliminar.setBackground(new java.awt.Color(0, 153, 255));
        btneliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btneliminar.setForeground(new java.awt.Color(255, 255, 255));
        btneliminar.setText("ELIMINAR");
        btneliminar.setBorder(null);
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 530, 80, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
     try {
            td.setDNI(txtdni.getText());
            td.setNombre(txtnombre.getText());
            td.setTelefono(txttelefono.getText());            
            td.setDireccion(txtdireccion.getText());
            tdbo.agregarCliente(td);
             listarCliente();

            JOptionPane.showMessageDialog(null, ":) se guardo corectamente");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: al guardar Tipo documento ");
        }
    }//GEN-LAST:event_btnguardarActionPerformed
 public boolean valida(){
    if (txtnombre.getText().equals("")) {
    JOptionPane.showMessageDialog(null, ":) NOMBRE ES REQUERIDO");
    return false;
     } else if (txtdni.getText().equals("")) {
    JOptionPane.showMessageDialog(null, ":) DNI ES REQUERIDO");
    return false;
    } else if (txttelefono.getText().equals("")) {
    JOptionPane.showMessageDialog(null, ":) telefono ES REQUERIDO");
    return false;
    } else if (txtdireccion.getText().equals("")) {
    JOptionPane.showMessageDialog(null, ":) DIRECCION ES REQUERIDO");
     return false;
    }         
    // If all validations pass

  return true;}

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        txtnombre.setText("");
        txtdni.setText("");
        txttelefono.setText("");
        txtdireccion.setText("");
        JOptionPane.showMessageDialog(null, "Campos limpiados.");
      }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
   try {
        // Obtener el índice de la fila seleccionada
        int filaSeleccionada = tablacliente.getSelectedRow();
        
        // Verificar si se ha seleccionado una fila
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Por favor selecciona un cliente para eliminar.");
            return; // Detener si no se ha seleccionado una fila
        }

        // Obtener el DNI del cliente de la fila seleccionada (suponiendo que está en la primera columna)
        String dniCliente = tablacliente.getValueAt(filaSeleccionada, 0).toString(); 
        
        // Inicializa el objeto Cliente
        Cliente td = new Cliente();
        td.setDNI(dniCliente); // Establecer el DNI en el objeto Cliente
        
        // Llamar al método para eliminar el cliente
        tdbo.eliminarCliente(td);
        
        // Actualizar la lista de clientes después de la eliminación
        listarCliente();
        
        // Mensaje de éxito
        JOptionPane.showMessageDialog(this, "Cliente eliminado exitosamente.");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }

    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
      /*  try {
            td.setDNI(txtdni.getText());
            td.setNombre(txtnombre.getText());
            td.setTelefono(txttelefono.getText()); 
            td.setDireccion(txtdireccion.getText());
         
            tdbo.modificarCliente(td);
            listarCliente();
            JOptionPane.showMessageDialog(null, ":) se guardo corectamente");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: al guardar Tipo documento ");
        }
 */
 try {
        // Obtener el índice de la fila seleccionada
        int filaSeleccionada = tablacliente.getSelectedRow();
        
        // Verificar si se ha seleccionado una fila
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Por favor selecciona un cliente para modificar.");
            return; // Detener si no se ha seleccionado una fila
        }

        // Obtener el DNI del cliente de la fila seleccionada (suponiendo que está en la primera columna)
        String dniCliente = tablacliente.getValueAt(filaSeleccionada, 0).toString();

        // Inicializa el objeto Cliente
        Cliente td = new Cliente();
        td.setDNI(dniCliente); // Establecer el DNI en el objeto Cliente

        // Obtener los nuevos datos de los campos de texto
        td.setNombre(txtnombre.getText());
        td.setTelefono(txttelefono.getText());
        td.setDireccion(txtdireccion.getText());

        // Llamar al método para modificar el cliente
        tdbo.modificarCliente(td);
        
        // Actualizar la lista de clientes después de la modificación
        listarCliente();
        
        // Mensaje de éxito
        JOptionPane.showMessageDialog(this, "Cliente modificado correctamente.");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void tablaclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaclienteMouseClicked
        int seleccion = tablacliente.rowAtPoint(evt.getPoint());
        txtdni.setText(tablacliente.getValueAt(seleccion, 0)+"");
        txtnombre.setText(tablacliente.getValueAt(seleccion, 1)+ "");
        txttelefono.setText(tablacliente.getValueAt(seleccion, 2)+ "");
        txtdireccion.setText(tablacliente.getValueAt(seleccion, 3)+ "");

        System.out.println(tablacliente);
    }//GEN-LAST:event_tablaclienteMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablacliente;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
