/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.camila.pe.cpresentacion;
import com.camila.pe.cmodelo.Compañia;
import com.camila.pe.cnegocio.CompañiaBO;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author PC
 */
public class JPCompañia extends javax.swing.JPanel {
    CompañiaBO cpbo = new  CompañiaBO();
    Compañia cp = new Compañia();
    String nro_compañia;
    /**
     * Creates new form JPCompañia
     */
    public JPCompañia() {
        initComponents();
        listarCompañia();
    }
    public void listarCompañia(){
        cpbo.listarCompañia(tablacompañia);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnro = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        btneliminar = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablacompañia = new javax.swing.JTable();
        btnmodificar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 255, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setText("COMPAÑIA");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel2.setText("NRO COMPAÑIA");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 247, -1, -1));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel3.setText("NOMBRE DE LA COMPAÑIA");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        txtnro.setBorder(null);
        add(txtnro, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 282, 380, 36));

        txtnombre.setBorder(null);
        add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 380, 35));

        btneliminar.setBackground(new java.awt.Color(255, 255, 0));
        btneliminar.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        btneliminar.setText("ELIMINAR");
        btneliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 520, 110, 40));

        btnguardar.setBackground(new java.awt.Color(255, 255, 0));
        btnguardar.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        btnguardar.setText("GUARDAR");
        btnguardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 110, 40));

        tablacompañia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablacompañia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablacompañiaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablacompañia);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 390, 350));

        btnmodificar.setBackground(new java.awt.Color(255, 255, 0));
        btnmodificar.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        btnmodificar.setText("MODIFICAR");
        btnmodificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });
        add(btnmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 520, 110, 40));

        jButton4.setBackground(new java.awt.Color(255, 255, 0));
        jButton4.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton4.setText("LIMPIAR");
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 520, 110, 40));

        btnlimpiar.setBackground(new java.awt.Color(255, 255, 0));
        btnlimpiar.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        btnlimpiar.setText("LIMPIAR");
        btnlimpiar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });
        add(btnlimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, 110, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
     try {
            cp.setNro_compañia(txtnro.getText());
            cp.setNombre(txtnombre.getText());
         
            cpbo.agregarCompañia(cp);
            listarCompañia();

            JOptionPane.showMessageDialog(null, ":) se guardo corectamente");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: al guardar Tipo documento ");
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
      txtnro.setText("");
      txtnombre.setText("");

        JOptionPane.showMessageDialog(null, "Campos limpiados.");
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
 try {
        // Obtener el índice de la fila seleccionada
        int filaSeleccionada = tablacompañia.getSelectedRow();
        // Obtener el DNI del cliente de la fila seleccionada (suponiendo que está en la primera columna)
        String nro_compañia = tablacompañia.getValueAt(filaSeleccionada, 0).toString();
        // Inicializa el objeto Cliente
        Compañia cp = new Compañia();
        cp.setNro_compañia(nro_compañia); // Establecer el DNI en el objeto Cliente
        // Obtener los nuevos datos de los campos de texto
        cp.setNombre(txtnombre.getText());
        // Llamar al método para modificar 
        cpbo.modificarCompañia(cp);
        // Actualizar 
        listarCompañia();
        
        // Mensaje de éxito
        JOptionPane.showMessageDialog(this, "Cliente modificado correctamente.");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void tablacompañiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablacompañiaMouseClicked
        int seleccion = tablacompañia.rowAtPoint(evt.getPoint());
        txtnro.setText(tablacompañia.getValueAt(seleccion, 0)+"");
        txtnombre.setText(tablacompañia.getValueAt(seleccion, 1)+ "");

        System.out.println(tablacompañia);
    }//GEN-LAST:event_tablacompañiaMouseClicked

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
 try {
        // Obtener el índice de la fila seleccionada
        int filaSeleccionada = tablacompañia.getSelectedRow();

        // Obtener el DNI del cliente de la fila seleccionada (suponiendo que está en la primera columna)
        String nrocompañia = tablacompañia.getValueAt(filaSeleccionada, 0).toString(); 
        
        // Inicializa el objeto Cliente
        Compañia cp = new Compañia();
        cp.setNro_compañia(nrocompañia); 
        
        // Llamar al método para eliminar el cliente
        cpbo.eliminarCompañia(cp);
        
        // Actualizar la lista de clientes después de la eliminación
        listarCompañia();        
        // Mensaje de éxito
        JOptionPane.showMessageDialog(this, "Cliente eliminado exitosamente.");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_btneliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablacompañia;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtnro;
    // End of variables declaration//GEN-END:variables
}
